server:
  port: 80
spring:
  application:
    name: cloud-consume-order
  cloud:
    consul:
      host: http://192.168.136.128
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}