server:
  port: 8003
spring:
  application:
    name: cloud-provide-hystrix-payment
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
         defaultZone:  http://localhost:7001/eureka/
  instance:
     prefer-ip-address: true
#     集群版
#        defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
