server:
  port: 80
spring:
  application:
    name: cloud-consume-fegin-order
service:
  payment:
    url: http://localhost:8001
    name: http://cloud-provide-payment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: cloud-consume-fegin-order80
    prefer-ip-address: true
# 设置open feign的默认超时时间，其底层使用了ribbon
ribbon:
#   指建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
   ReadTimeout: 5000
#   指的是建立连接后从服务器读取到可用资源所用的时间
   ConnectTimeout: 10000
logging:
  level:
     com.mytest.service.PaymentFeignService: debug
