server:
  port: 9527
spring:
  application:
    name: springcloud-gateway9527
  cloud:
    gateway:
      routes:
        - id: payment_router1
#          uri: http://localhost:8001
          uri: lb://cloud-provide-payment
          predicates:
             - Path=/provide/**
        - id: payment_router2
#          uri: http://localhost:8001
          uri: lb://cloud-provide-payment
          predicates:
            - Path=/payment/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-gateway9527
    prefer-ip-address: true