server:
  port: 8002
spring:
  application:
    name: cloud-provide-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.136.128:8889/mytest?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
#    initialization-mode: always
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.mytest.entity
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
      instance-id: cloud-provide-payment7002
      prefer-ip-address: true